{% set name = "plio" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 167595af3da54888428a28d15d56d05da48fa5a0429a88119cc6c0879088ecdf

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - pvl >=1.0
    - protobuf
    - gdal
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - h5py
    - scipy
    - pyproj
    - jinja2

test:
  imports:
    - plio

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: Unlicense
  license_file: LICENSE.md
  summary: input/output library for planetary science data

extra:
  recipe-maintainers:
    - jlaura
    - acpaquette
    - jessemapel
