{% set name = "plio" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f02f93270552ad609b75ebf992b5531316cb0e5716853af928ba5b687b951cfb

build:
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run: 
    - python
    - numpy
    - pvl
    - protobuf
    - gdal
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - h5py
    - scipy
    - pyproj
    - jinja2

test:
  imports:
    - plio

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: Public Domain
  license_file: LICENSE.md
  summary: input/output library for planetary science data

extra:
  recipe-maintainers:
    - jlaura
