# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "efxozKZvJSOCevv6ffRoloDbQ5OxjFK8J5A6iKkAAUm0kzORrN3nfkV8+QwSA//fkL9OAKdPgF9FN9QR8+Nq6RhEqWI3USZOCe1q0L6wLmqlshyC2TBU3+4PhMcEDLkpFEKPmsxvNI7rP0gpv+0rkdAui1rTS6+Ta60oDuMa1yyB5nfwp58mSKzr/n7dxFwznZYPTy05mhHBh+/8jdgLGfNoXIEvVZSw46qIwsa8KjkDNouIdSEuvdT19QRK16rE4Cu9V+yzLGizuwoh0HlNnqiJgqHuUsXLUoU8pY4eQoYuECUqwRuj2pDc4vjLc0Cs6aTw/Zq/oyVfiRgoS8hZ/XWY5vO5PgUWOxlC9JO7PB1aVgIVU1Z0DrlL6qwQMqBMccAY7N9jfQ399AFyDirEFoXWyvNVu8kQ4NzZm1wVKr8WE79yBZfwp4JzADNKMtD11H574KblFYjz2VIGls1VIlHk9vCnDwTuBBMgGQhYaFFdiWupQxe6NKdVIZuKFC6KCFVbMOnr9/UVazROOxEsGJ/E6vedxHI3IZCU6LHFUM1rNdEQiMJ2rZhzkPTr8CFxyfpwCO94/OY5CWVNwMSo27QAs1Eym5yXzyMK9s8BC7ENFgKh8J1rr39O+cumiyC1Edx7y2i4emn9GpS/iFrPiaBCm8UfrztSaEvpaUo8tso="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml